### ISSUE TITLE
No listner

### ISSUE THREAD

**Issue by Bigpapa-R** [oracle/big-data-lite#2]
Please could you assist with how to troubleshoot the oracle listener on the big data lite.

I tried running  sh genloc_moviefact.sh from the /home/oracle/movie/moviework/osch director after supplying the password i got the following error:
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:677)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:706)
        at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:390)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:262)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:199)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:177)
        at oracle.hadoop.utils.DBUtils$ConnectionBuilder.getConnection(DBUtils.java:364)
        at oracle.hadoop.utils.DBUtils$ConnectionBuilder.getConnection(DBUtils.java:257)
        at oracle.hadoop.exttab.ExternalTable.getConnection(ExternalTable.java:923)
        at oracle.hadoop.exttab.ExternalTable.run(ExternalTable.java:3165)
        at oracle.hadoop.exttab.ExternalTable.run(ExternalTable.java:3255)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at oracle.hadoop.exttab.ExternalTable.main(ExternalTable.java:3368)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:520)
        at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:488)
        at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:596)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:242)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1421)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:523)
        ... 20 more
Caused by: java.io.IOException: Connection refused, socket connect lapse 1 ms. localhost/127.0.0.1 1521 0 1 true
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:208)
        at oracle.net.nt.ConnOption.connect(ConnOption.java:160)
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:465)
        ... 25 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:458)
        at sun.nio.ch.Net.connect(Net.java:450)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:66)
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:164)
        ... 27 more

**Comment by KeithLaker** [comment]
Did you start the database instance and the listener? Try running SQL Developer and see if you can connect to the database. If SQL Developer works then this should all work

**Comment by Bigpapa-R** [comment]
I try running SQL Developer and got the error in quotes below:
"An error was encountered performing the requested operation:

IO Error: The Network Adapter could not establish the connection

Vendor code 17002"

I also tried running sqlplus from the prompt and got error in quotes below: 

"[oracle@bigdatalite ~]$ sqlplus

SQL*Plus: Release 12.1.0.2.0 Production on Tue Jan 26 09:52:51 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Enter user-name: oracle
Enter password: 
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Additional information: 3640
Additional information: 1742002911
Process ID: 0
Session ID: 0 Serial number: 0"

**Comment by Bigpapa-R** [comment]
Just to add that I resolved this issue by login into sqlplus as sysdba, startup db and start listener.
